const data = {
    users: [
      {
        name: 'Navas',
        email: 'cknavas123@gmail.com',
        // password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
      {
        name: 'Liyana',
        email: 'user@example.com',
        // password: bcrypt.hashSync('123456'),
        isAdmin: false,
      },
    ],
    products: [
      {
        name: 'Free Shirt',
        productid: 'free-shirt',
        category: 'Shirts',
        image: '/images/shirt1.jpg',
        price: 70,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Fit Shirt',
        productid: 'fit-shirt',
        category: 'Shirts',
        image: '/images/shirt2.jpg',
        price: 80,
        brand: 'Adidas',
        rating: 3.2,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Slim Shirt',
        productid: 'slim-shirt',
        category: 'Shirts',
        image: '/images/shirt3.jpg',
        price: 90,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 3,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Golf Pants',
        productid: 'golf-pants',
        category: 'Pants',
        image: '/images/pants1.jpg',
        price: 90,
        brand: 'Oliver',
        rating: 2.9,
        numReviews: 13,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        name: 'Fit Pants',
        productid: 'fit-pants',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 95,
        brand: 'Zara',
        rating: 3.5,
        numReviews: 7,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        name: 'Classic Pants',
        productid: 'classic-pants',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 2.4,
        numReviews: 14,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };
  
  export default data;